apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb2
          image: mongo
          ports:
            - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "root"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "mongopwd"
          - name: MONGODB_DATABASE
            value: "rotten-potatoes-db"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: rotten-potatoes-app
          image: franciscoviana/rotten-potatoes:v1
          ports:
          - containerPort: 5000
          env:
          - name: MONGODB_DB
            value: rotten-potatoes-db 
          - name: MONGODB_HOST
            value: mongodb2 
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_USERNAME
            value: "root"
          - name: MONGODB_PASSWORD
            value: "mongopwd"
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - port: 80
    targetPort: 5000
    # nodePort: 30080
  # type: NodePort
  type: LoadBalancer
