apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
          - name: MONGODB_DB
            value: root 
          - name: MONGODB_HOST
            value: localhost 
          - name: MONGODB_PORT
            value: 27017
          - name: MONGODB_USERNAME
            value: "mongouser"
          - name: MONGODB_PASSWORD
            value: "mongopwd"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: rotten-potatoes-app
          image: franciscoviana/rotten-potatoes
          ports:
          - containerPort: 3000
          env:
          - name: MONGODB_DB
            value: root 
          - name: MONGODB_HOST
            value: localhost 
          - name: MONGODB_PORT
            value: 27017
          - name: MONGODB_USERNAME
            value: "mongouser"
          - name: MONGODB_PASSWORD
            value: "mongopwd"
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000
  type: NodePort
  # type: LoadBalancer
