name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout da base de código
        uses: actions/checkout@v3.6.0
        
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USR }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Construindo a imagem do rotten-potatoes
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
           franciscoviana/rotten-potatoes:${{github.run_number}}
           franciscoviana/rotten-potatoes:latest
    
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout da base de código
        uses: actions/checkout@v3.6.0

      - name: Autenticação na AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Configuração do Kubeconfig
        shell: bash
        run: |
          aws eks update-kubeconfig --name ${{ secrets.AWS_EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy do rotten-potatoes no cluster Kubernetes 
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            deployment.yaml
          images: |
            franciscoviana/rotten-potatoes:${{github.run_number}}
